import photosJson from "./photos.json";

export type Photo = {
  src: string;
  thumb: string;
  alt: string;
  title: string;
  location: string;
  year: number;
  orientation: "landscape" | "portrait";
  width: number;
  height: number;
  blurDataURL: string;
};

/** Generated by scripts/optimize-photos.mjs — edit photos-raw/captions.json, not this. */
export const photos = photosJson as Photo[];
